### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by hungaikev** [nigelnindo/africastalking-scala-wrapper#5]
https://github.com/nigelnindo/africastalking-scala-wrapper/blob/master/src/main/scala/api/validations/SMSValidations.scala

Instead of defining your own Validation type, have thought of using this one from the [cats package](http://typelevel.org/cats/datatypes/validated.html)

**Comment by nigelnindo** [comment]
@hungaikev will go through [Validated](http://typelevel.org/cats/datatypes/validated.html) from cats. Was looking at providing default validations, and allowing the user of the lib extend with their own validations too. If **Validated** provides such functionality, then its a great choice.
